version: '3'
services:
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ 
    ports:
      - '5432:5432'
    networks:
      - strapi